sudo: required

language: cpp

os: linux

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "hGuLid4OBUhZmy1phVoNkycc1QjoMHXLpSK5mnglEgx1/pGPOxmaZ4Aik625iTkQNFtl4yj1a7Y1Dd/kIjjut8ohjvg3Eu08FZ+Ug5suLpqHPxlECZHYuHT4diuHO3ZFMLQeS3A+q1I07azN06zJvqtNFQYPmMFHE/5+pA/8Baq3MdmEdUxXioFBCOnEqJmlzEp+PByxeKDRZrE9lDXSWLZUEN+5H8tPjpPBR7qjyWdXmPo9G2HM3JzyclJ4MhSzE0REj11q4mkNKygWOJMOl4b2by/Csm2rZH6gciY2aPJLFkukKqDQERt/PI4lyqspqmVw8aJfp1NIhqkk11H6qXE0ypBOdc9xPT5I/A55ydnvPJxD1W34oSnex5L5MpfThw0UAuY6I7xdwAccEtUODFE2s280BmAfC2u7ktwbvkIi+KUfCfE69BWp1eD4i2/exTwd+GRmDUEJIRiJF0yJKm+m+YSAIljoTytFtVyjfG/ge1pC12SEZ8XUFFPewIq/qz7e841inV4glgW8vqBIEH41QIUbPXe94RM1TvqPNMIrIz8Gaikl5nrvLw4bwmRNnioxMBM9pHUbCiMqFy2qhXIfnt8nUFAcp+E4eV6bANf6waMyEBpTIBUxoJD4K+dH8t816kPhWev/RrbsLBuokWCTtLSNXCpsUYgWHQicT/c="
   - V=1
   - COVERITY_SCAN_PROJECT_NAME=otcshare/iotivity-node
   - COVERITY_SCAN_NOTIFICATION_EMAIL=gabriel.schulhof@intel.com
   - COVERITY_SCAN_BRANCH_PATTERN="${TRAVIS_BRANCH}"
   - COVERITY_SCAN_BUILD_COMMAND="npm install"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libcurl4-openssl-dev
    - uuid-dev
    - g++-4.8
    - libboost-all-dev

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
  - sudo update-alternatives --config gcc
  - sudo update-alternatives --config g++
  - gcc --version
  - g++ --version
  - rm -rf ~/.nvm
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.31.7/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install stable

script:
  - wget -qO- 'https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh' | bash
